# Global Configuration
global:
  collect_stats: false # persistence mode [open|closed]
  audit_log_rotation_enabled: true
  audit_log_rotation: 20
  response_log_rotation_enabled: true
  response_log_rotation: 20
  web_ui:
    port: 7051 # Web UI Port [/ => json response, /stats => if collect_stats open you can show statistics]
    failure_status_code: 400 # Failure status code for json response ( if any of services down )
    audit_log_limit: 10
    response_log_limit: 10
  notifiers:
    threshold: 30
    services:
      slack:
        slack_url: "https://hooks.slack.com/services/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"
        slack_channel: "#general"
        slack_username: "P.U.L.S.E."
        message: "Service `${service_name}` has been down since `${duration}`."
      email:
        smtp_host: "localhost"
        smtp_port: 1025
        smtp_username: "test"
        smtp_password: "test"
        mail_from: "alert@pulse.com"
        mail_title: "Down Alert"
        mail_recipients:
          - me@batikansenemoglu.com
          - batikansenemoglu@gmail.com
        message: "Service `${service_name}` has been down since `${duration}`."
  retry_policy:
    timeout: 3s
    down_threshold: 3
    up_threshold: 3
  check_interval: 10s

# Health Checks
health_checks:
  custom_test:
    type: custom
    source: python ./custom/ping.py
    check_interval: 10s
    retry_policy:
      timeout: 3s
      down_threshold: 3
      up_threshold: 3
    notifiers:
      threshold: 15
      services:
        slack:
          slack_url: "https://hooks.slack.com/services/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"
          slack_channel: "#general"
          slack_username: "P.U.L.S.E."
          message: "Service `${service_name}` has been down since `${duration}`."
        email:
          smtp_host: "localhost"
          smtp_port: 1025
          smtp_username: "test"
          smtp_password: "test"
          mail_from: "alert@pulse.com"
          mail_title: "Down Alert"
          mail_recipients:
            - me@batikansenemoglu.com
            - batikansenemoglu@gmail.com
          message: "Service `${service_name}` has been down since `${duration}`."