
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = ">=1.0.0-rc2"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  name = "github.com/Kelindar/binary"
  version = "1.0.4"

[[constraint]]
  name = "gopkg.in/restruct.v1"
  version = "1.0.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "4.0.2"

[[constraint]]
  name = "github.com/ashwanthkumar/slack-go-webhook"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/gocql/gocql"

[[constraint]]
  branch = "master"
  name = "github.com/couchbase/go-couchbase"

[[constraint]]
  branch = "master"
  name = "github.com/tsuna/gohbase"

[[constraint]]
  branch = "master"
  name = "github.com/rtt/Go-Solr"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/dimiro1/banner"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  name = "github.com/hako/durafmt"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"
